pipeline:
  name: Kustomize
  identifier: Kustomize
  tags: {}
  projectIdentifier: Scrap
  orgIdentifier: default
  stages:
    - stage:
        name: staging
        identifier: staging
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: helloworld
          environment:
            environmentRef: staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: orbstaging
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: true
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: mycustomvar
      type: String
      description: ""
      required: false
      value: test
